config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "pages#home"

  get "my_portfolio", to: "users#my_portfolio"

  get "search", to: "stocks#search"

  resources :user_stocks, only: [:create, :destroy]

  get "user_stocks", to: "user_stocks#create"

  get "my_friends", to: "friends#my_friends"

  get "search_friend", to: "search_friend#search"

  resources :friends, only: [:create, :destroy]

  get "friends", to: "friends#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord


  # def self.new_lookup(company)
  #
  #   secret_key = Rails.application.credentials.iex_cloud[:secret_key]
  #   public_key = Rails.application.credentials.iex_cloud[:public_key]
  #   client = IEX::Api::Client.new(
  #     secret_token: secret_key,
  #     publishable_token: public_key,
  #     endpoint: 'https://cloud.iexapis.com/v1'
  #   )
  #   return client.price(company)
  #
  # end

  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(company)
    client = Stock.find_by(ticker: company)
    return client
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def my_friends
    @friends = current_user.friends
  end

  def create
    @add_friend = Friendship.create(user: current_user, friend_id: params[:friend].to_i)
    redirect_to my_friends_path
  end


  def destroy
    @friend = Friendship.where(user_id: current_user.id, friend_id: params[:id]).first
    if @friend.destroy
      redirect_to my_friends_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end
  
end

app/controllers/search_friend_controller.rb
class SearchFriendController < ApplicationController

  def search
    @friend = User.find_by(email: params[:friend])
    if @friend
      respond_to do |format|
        format.js { render partial: "friends/result" }
      end
    end
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial:"users/result" }
        end
      end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock_name = Stock.find(params[:stock]).ticker
    stock = Stock.new_lookup(stock_name)
    @user_stock = UserStock.create(user: current_user, stock: stock)
    redirect_to my_portfolio_path
  end

  def destroy
    @stock = UserStock.where(user_id: current_user.id, stock_id: params[:id]).first
    if @stock.destroy
      redirect_to my_portfolio_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @stocks = current_user.stocks
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/_result.js.erb
const result = `
  <% if @friend %>
    <h5 class="my-3">Result </h5>
    <div class="card mb-5" style="width: 800px">
        <div class="card-body bg-secondary">
            <span class="card-subtitle mb-2 text-white mx-5">Email: <%= @friend.email %></span>
            <%= link_to "Follow", friends_path(user:current_user, friend:@friend), class: "btn btn-warning" %>
        </div>
    </div>
  <%else%>
    <div class="alert alert-warning">Stock not found</div>
  <%end%>
`



document.querySelector("#friend-result").innerHTML = result

app/views/friends/my_friends.html.erb
<h1>My Friends</h1>
<div class="search-area py-3">

  <%= form_with(url: search_friend_path, local: false, method: :get) do |form| %>
    <%= form.label :friend, class: "form-label" %>
    <%= form.text_field :friend, class: "form-control", id: "exampleDataList", placeholder: "Type to search..." %>
    <%= form.submit "Search", class: "btn btn-success my-2" %>
  <%end%>

</div>

<div id="friend-result">

</div>


<% if @friends.any? %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.email %></td>
        <td><%= link_to "Unfollow", friend_path(friend), class: "btn btn-warning", method: :delete %></td>
      </tr>
    <%end%>
    </tbody>
  </table>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <%#= link_to "STOCK-TRACKER", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
          <li class="nav-item">
            <%= link_to "Portfolio", my_portfolio_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
          <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
        </li>
          <% if signed_in? %>
            <li class="nav-item">
              <p class="nav-link"><%= current_user.email %></p>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link btn btn-danger text-white mx-2" %>
            </li>
          <%else%>
            <li class="nav-item">
              <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Signin", new_user_session_path, class: "nav-link" %>
            </li>
          <%end%>
      </ul>
<!--      <form class="d-flex" role="search">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navigation" %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home page</h1>
<%= link_to "Signout", destroy_user_session_path, method: :delete%>

app/views/users/_result.js.erb
const result = `
  <% if @stock %>
    <h5 class="my-3">Result </h5>
    <div class="card mb-5" style="width: 800px">
        <div class="card-body bg-secondary">
            <span class="card-subtitle mb-2 text-white mx-5">Symbol: <%= @stock.ticker %></span>
            <span class="card-subtitle mb-2 text-white mx-5">Name: <%= @stock.name %></span>
            <span class="card-subtitle mb-2 text-white mx-5">Price: <%= @stock.last_price %></span>
            <%= link_to "Add to portfolio", user_stocks_path(user:current_user, stock:@stock), class: "btn btn-warning" %>
        </div>
    </div>
  <%else%>
    <div class="alert alert-warning">Stock not found</div>
  <%end%>
`



document.querySelector("#result").innerHTML = result

//document.querySelector("#result").innerHTML = "<%#= j render partial:"users/result.html" %>"

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area py-3">

  <%= form_with(url: search_path, local: false, method: :get) do |form| %>
    <%= form.label :stock, class: "form-label" %>
    <%= form.text_field :stock, class: "form-control", id: "exampleDataList", placeholder: "Type to search..." %>
    <%= form.submit "Search", class: "btn btn-success my-2" %>
  <%end%>

</div>

<div id="result">

</div>


<% if @stocks.any? %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Ticker</th>
      <th scope="col">Last Price</th>
      <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.ticker %></td>
        <td><%= stock.last_price %></td>
        <td><%= link_to "Delete", user_stock_path(stock), class: "btn btn-warning", method: :delete %></td>
      </tr>
    <%end%>
    </tbody>
  </table>
<%end%>